trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest
- task: DotNetCoreCLI@2
  displayName: Install Playwright CLI
  inputs:
    command: custom
    custom: 'tool '
    arguments: install Microsoft.Playwright.CLI
- task: DotNetCoreCLI@2
  displayName: 'Build test project'
  inputs:
    command: 'build'
    projects: 'PlaywrightTest1/PlaywrightTest1.csproj'
- task: DotNetCoreCLI@2
  displayName: Run Playwright Install
  inputs:
    command: custom
    custom: 'tool '
    arguments: run playwright install
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'PlaywrightTest1/PlaywrightTest1.csproj'
    arguments: '-e BROWSER=chromium'
    testRunTitle: 'Chrome results'
    buildProperties: 
